lab06/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tienda/', include('tienda.urls')),
    path('admin/', admin.site.urls),
]

tienda/urls.py
from django.urls import path 

from .import views

app_name = 'tienda'

urlpatterns = [
    path('', views.index, name ='index'),
    path('producto/<int:producto_id>/', views.producto, name='producto'),
    path('categoria/<int:categoria_id>/', views.productos_por_categoria, name='productos_por_categoria'),
]

tienda/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    pub_date = models.DateTimeField('fecha de registro',auto_now=True)
    
    def __str__(self):
        return self.nombre

class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=6,decimal_places=2)
    stock = models.IntegerField(default=0)
    imagen_url = models.CharField(max_length=200, null=True, blank=True)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.nombre

tienda/views.py
from django.shortcuts import get_object_or_404, render

from tienda.models import Categoria, Producto

# Create your views here.
def index(request):
    product_list = Producto.objects.order_by('nombre')[:6]
    categorias = Categoria.objects.all()
    context = {'product_list': product_list, 'categorias': categorias, 'detalle':True}
    return render(request,'index.html', context)

def producto (request, producto_id):
    producto = get_object_or_404(Producto, pk=producto_id)
    categorias = Categoria.objects.all()
    context = {'producto': producto, 'categorias': categorias, 'detalle': True}
    return render(request, 'producto.html', context)

def productos_por_categoria(request, categoria_id):
    categoria = get_object_or_404(Categoria, pk=categoria_id)
    productos = Producto.objects.filter(categoria=categoria)
    return render(request, 'productos_por_categoria.html', {'categoria': categoria, 'productos': productos})

tienda/templates/index.html
{% extends "layout.html" %}
{% block content %}

<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li> 
      <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <img class="d-block img-fluid" src="https://www.las2orillas.co/wp-content/uploads/2023/08/gaseosas-parecidas-a-la-Coca-Cola-1.jpg" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block img-fluid" src="https://s2.abcstatics.com/lavozdigital/www/multimedia/provincia/2022/12/05/chocolate-U76235656031WKO-1200x630@abc.jpg" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block img-fluid" src="https://static.abc.es/media/bienestar/2020/02/16/cookies-U303042264459ddC--1200x630@abc.jpg" alt="Third slide">
      </div>
      <div class="carousel-item">
        <img class="d-block img-fluid" src="https://www.abc.es/media/bienestar/2020/06/15/patatas-fritas-acrilamida-1-k7GE--1200x630@abc.jpeg" alt="fourth slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class="row">
    
    {% for prod in product_list %}
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card h-100">
        <a href="producto/{{ prod.id }}/"><img class="card-img-top" src="{{ prod.imagen_url }}" alt=""></a>
        <div class="card-body">
          <h4 class="card-title">
            <a href="producto/{{ prod.id }}/">{{ prod.nombre }}</a>
          </h4>
          <h5>S/ {{ prod.precio }}</h5>
          <p class="card-text">Categoría: {{ prod.categoria.nombre }}</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock %}

tienda/templates/layout.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tienda</title>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/shop.css' %}" rel="stylesheet">
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Productos</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/tienda/">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">
        {% if detalle %}
          <div class="col-lg-3">
            <h1 class="my-4">Categoria</h1>
            <div class="list-group">
                {% for categoria in categorias %}
                <a href="{% url 'tienda:productos_por_categoria' categoria.id %}" 
                class="list-group-item">{{ categoria.nombre }}</a>
                {% endfor %}
            </div>
          </div>
        {% endif %}
        <div class="col-lg-9">

          <!-- Block Content -->
          {% block content %}{% endblock %}
          <!-- /Block Content -->
          
        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Yaseni Sandoval - 2024</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

tienda/templates/producto.html
{% extends "layout.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-6">
            <img class="img-fluid" src="{{ producto.imagen_url }}" alt="{{ producto.nombre }}">
        </div>
        <div class="col-lg-6">
            <h1>Nombre: {{ producto.nombre }}</h1>
            <p class="lead">Precio: S/ {{ producto.precio }}</p>
            <p>Categoría: {{ producto.categoria.nombre }}</p>
            <p>Stock: {{ producto.stock }}</p>
            <p>Fecha de registro: {{ producto.pub_date }}</p>
        </div>
    </div>
</div>
{% endblock %}

tienda/templates/productos_por_categoria.html
{% extends "layout.html" %}
{% block content %}
<div class="container mt-5">
    <h2>Productos de la categoría: {{ categoria.nombre }}</h2>
    <div class="row">
        {% for producto in productos %}
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
                    <img class="card-img-top" src="{{ producto.imagen_url }}" alt="{{ producto.nombre }}">
                <div class="card-body">
                    <h5>{{ producto.nombre }}</h5>
                    <p class="lead">Precio: S/ {{ producto.precio }}</p>
                    <p>Stock: {{ producto.stock }}</p>
                    <p>Fecha de registro: {{ producto.pub_date }}</p>
                </div>
                
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}